# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb4a72a1c722b2862825b48ba24cd7d1db6b197eab319c6c93ffdcaaf8571db71377cd0a2e70ee7e08a3fc9887d19242b87adf7bbb1a798452051aef7aef500f

test:
  secret_key_base: 9848bd250f7d021644680668b10fb8c15e508219b5c8068bca2c2018f9a772ed142c5b01734f8bbfd88c0008d408587df6f4337af4ca9ce7cd5d7362f609fbba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
